name: appwrite_function
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dart_appwrite: ^6.0.1

dev_dependencies:
  lints: ^1.0.1
